// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>



QT_DECLARE_EXTERN_RESOURCE(qmake_Quickshell_Nigiri)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Quickshell_Nigiri)

class Quickshell_NigiriPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Quickshell_NigiriPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Quickshell_Nigiri)

QT_KEEP_RESOURCE(qmake_Quickshell_Nigiri)
    }
};



#include "quickshell-mac-nigiriplugin_Quickshell_NigiriPlugin.moc"
