// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>



QT_DECLARE_EXTERN_RESOURCE(qmake_Quickshell)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Quickshell)

class QuickshellPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QuickshellPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Quickshell)

QT_KEEP_RESOURCE(qmake_Quickshell)
    }
};



#include "quickshell-coreplugin_QuickshellPlugin.moc"
