// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>



QT_DECLARE_EXTERN_RESOURCE(qmake_Quickshell_Services_UPower)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Quickshell_Services_UPower)

class Quickshell_Services_UPowerPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Quickshell_Services_UPowerPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Quickshell_Services_UPower)

QT_KEEP_RESOURCE(qmake_Quickshell_Services_UPower)
    }
};



#include "quickshell-mac-upowerplugin_Quickshell_Services_UPowerPlugin.moc"
