// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>



QT_DECLARE_EXTERN_RESOURCE(qmake_Quickshell_Wayland)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Quickshell_Wayland)

class Quickshell_WaylandPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Quickshell_WaylandPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Quickshell_Wayland)

QT_KEEP_RESOURCE(qmake_Quickshell_Wayland)
    }
};



#include "quickshell-mac-waylandplugin_Quickshell_WaylandPlugin.moc"
