// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>



QT_DECLARE_EXTERN_RESOURCE(qmake_Quickshell__Window)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Quickshell__Window)

class Quickshell__WindowPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Quickshell__WindowPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Quickshell__Window)

QT_KEEP_RESOURCE(qmake_Quickshell__Window)
    }
};



#include "quickshell-windowplugin_Quickshell__WindowPlugin.moc"
