// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_quickshell_widgets)
QT_DECLARE_EXTERN_RESOURCE(qmake_Quickshell_Widgets)
QT_DECLARE_EXTERN_RESOURCE(quickshell_widgets_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Quickshell_Widgets)

class Quickshell_WidgetsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Quickshell_WidgetsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Quickshell_Widgets)
QT_KEEP_RESOURCE(qmlcache_quickshell_widgets)
QT_KEEP_RESOURCE(qmake_Quickshell_Widgets)
QT_KEEP_RESOURCE(quickshell_widgets_raw_qml_0)
    }
};



#include "quickshell-widgetsplugin_Quickshell_WidgetsPlugin.moc"
