// Copyright (C) 2023 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR BSD-3-Clause

// This file was generated by the qt_add_resources command.
// Qt-Security score:significant reason:default

#include <QtCore/qtsymbolmacros.h>

QT_DECLARE_EXTERN_RESOURCE(quickshell_widgets_raw_qml_0)

namespace {
    struct resourceReferenceKeeper {
        resourceReferenceKeeper() { QT_KEEP_RESOURCE(quickshell_widgets_raw_qml_0) }
    } resourceReferenceKeeperInstance;
}
