// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>



QT_DECLARE_EXTERN_RESOURCE(qmake_Quickshell_Bluetooth)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Quickshell_Bluetooth)

class Quickshell_BluetoothPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Quickshell_BluetoothPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Quickshell_Bluetooth)

QT_KEEP_RESOURCE(qmake_Quickshell_Bluetooth)
    }
};



#include "quickshell-mac-bluetoothplugin_Quickshell_BluetoothPlugin.moc"
